# application-dev.yml
spring:
  datasource:
    url: jdbc:h2:mem:studentdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
logging:
  level:
    com.studentmanagement: DEBUG